on:
  push:
    branches:
      - main
  workflow_dispatch:


# aarch64-apple-darwin
# aarch64-unknown-linux-gnu
# x86_64-apple-darwin
# x86_64-pc-windows-msvc
# x86_64-unknown-linux-musl

jobs:
  build-linux:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        target: ["x86_64-unknown-linux-musl", "aarch64-unknown-linux-gnu"]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install deps
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install zig cargo-zigbuild

      - name: Build ${{ matrix.target }}
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          cargo zigbuild --release --target ${{ matrix.target }}