on:
  workflow_dispatch:


# aarch64-apple-darwin
# aarch64-unknown-linux-gnu
# x86_64-apple-darwin
# x86_64-pc-windows-msvc
# x86_64-unknown-linux-musl

jobs:
  build-linux:
    strategy:
      matrix:
        target: ["x86_64-unknown-linux-musl", "aarch64-unknown-linux-gnu"]
    run-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Build ${{ matrix.target }}
        run: cargo zigbuild --release --target ${{ matrix.target }}