permissions:
  "contents": "write"
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release Tag
        required: true
        type: string


# aarch64-apple-darwin
# aarch64-unknown-linux-gnu
# x86_64-apple-darwin
# x86_64-pc-windows-msvc
# x86_64-unknown-linux-musl

jobs:
  build-linux:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        target: ["x86_64-unknown-linux-musl"]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install deps
        run: |
          # eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          # brew install zig cargo-zigbuild

      - name: Build ${{ matrix.target }}
        run: |
          # eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          cargo build --release --target ${{ matrix.target }}

          ./generate_release_files.sh ${{ matrix.target }}

      - name: Upload files to release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ inputs.tag }} artifacts/*

